driving_direction_compliance_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.driving_direction_compliance.DrivingDirectionComplianceStatistics
  _convert_: 'all'
  name: 'driving_direction_compliance'
  category: 'Planning'
  metric_score_unit: 'bool'

  driving_direction_compliance_threshold: 2 # [m] Driving in opposite direction up to this threshold isn't considered violation
  driving_direction_violation_threshold: 6 # [m] Driving in opposite direction above this threshold isn't tolerated
  time_horizon: 1 # [s] time horizon in which movement of the vehicle along baseline direction is computed.

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    lane_change_metric: ego_lane_change_statistics
