ego_is_making_progress_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_is_making_progress.EgoIsMakingProgressStatistics
  _convert_: 'all'
  name: 'ego_is_making_progress'
  category: 'Planning'
  metric_score_unit: 'bool'
  min_progress_threshold: 0.2

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    ego_progress_along_expert_route_metric: ego_progress_along_expert_route_statistics
