ego_is_comfortable_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_is_comfortable.EgoIsComfortableStatistics
  _convert_: 'all'
  name: 'ego_is_comfortable'
  category: 'Violations'
  metric_score_unit: 'bool'

  required_metrics:
    # Parameter: base metric name
    ego_jerk_metric: ego_jerk_statistics
    ego_lat_acceleration_metric: ego_lat_acceleration_statistics
    ego_lon_acceleration_metric: ego_lon_acceleration_statistics
    ego_lon_jerk_metric: ego_lon_jerk_statistics
    ego_yaw_acceleration_metric: ego_yaw_acceleration_statistics
    ego_yaw_rate_metric: ego_yaw_rate_statistics
