_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types:                     # List of scenario types to include
  - accelerating_at_crosswalk
  - accelerating_at_stop_sign
  - accelerating_at_stop_sign_no_crosswalk
  - accelerating_at_traffic_light
  - accelerating_at_traffic_light_with_lead
  - accelerating_at_traffic_light_without_lead
  - behind_bike
  - behind_long_vehicle
  - behind_pedestrian_on_driveable
  - behind_pedestrian_on_pickup_dropoff
  - changing_lane
  - changing_lane_to_left
  - changing_lane_to_right
  - changing_lane_with_lead
  - changing_lane_with_trail
  - crossed_by_bike
  - crossed_by_vehicle
  - following_lane_with_lead
  - following_lane_with_slow_lead
  - following_lane_without_lead
  - high_lateral_acceleration
  - high_magnitude_jerk
  - high_magnitude_speed
  - low_magnitude_speed
  - medium_magnitude_speed
  - near_barrier_on_driveable
  - near_construction_zone_sign
  - near_high_speed_vehicle
  - near_long_vehicle
  - near_multiple_bikes
  - near_multiple_pedestrians
  - near_multiple_vehicles
  - near_pedestrian_at_pickup_dropoff
  - near_pedestrian_on_crosswalk
  - near_pedestrian_on_crosswalk_with_ego
  - near_trafficcone_on_driveable
  - on_all_way_stop_intersection
  - on_carpark
  - on_intersection
  - on_pickup_dropoff
  - on_stopline_crosswalk
  - on_stopline_stop_sign
  - on_stopline_traffic_light
  - on_traffic_light_intersection
  - starting_high_speed_turn
  - starting_left_turn
  - starting_low_speed_turn
  - starting_protected_cross_turn
  - starting_protected_noncross_turn
  - starting_right_turn
  - starting_straight_stop_sign_intersection_traversal
  - starting_straight_traffic_light_intersection_traversal
  - starting_u_turn
  - starting_unprotected_cross_turn
  - starting_unprotected_noncross_turn
  - stationary
  - stationary_at_crosswalk
  - stationary_at_traffic_light_with_lead
  - stationary_at_traffic_light_without_lead
  - stationary_in_traffic
  - stopping_at_crosswalk
  - stopping_at_stop_sign_no_crosswalk
  - stopping_at_stop_sign_with_lead
  - stopping_at_stop_sign_without_lead
  - stopping_at_traffic_light_with_lead
  - stopping_at_traffic_light_without_lead
  - stopping_with_lead
  - traversing_crosswalk
  - traversing_intersection
  - traversing_narrow_lane
  - traversing_pickup_dropoff
  - traversing_traffic_light_intersection
  - waiting_for_pedestrian_to_cross
scenario_tokens: null               # List of scenario tokens to include

log_names: ${splitter.log_splits.test}  # Use all logs present in the test split
map_names: null                     # Filter scenarios by map names

num_scenarios_per_type: 100         # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: true          # Whether to remove scenarios where the mission goal is invalid
shuffle: false                      # Whether to shuffle the scenarios
