hydra:
  run:
    dir: .
  output_subdir: null            # Store hydra's config breakdown here for debugging
  searchpath:                                                   # Only <exp_dir> in these paths are discoverable
    - pkg://nuplan.planning.script.config.common
    - pkg://nuplan.planning.script.experiments                  # Put experiments configs in script/experiments/<exp_dir>


defaults:
  - default_common
  - simulation_metric:
      - default_metrics
  - override hydra/job_logging: none                            # Disable hydra's logging
  - override hydra/hydra_logging: none                          # Disable hydra's logging

log_config: False                                  # Whether to log the final config after all overrides and interpolations
port_number: 5006
simulation_path: null
resource_prefix: null
profiler_path: null
async_scenario_rendering: True                     # Setting this to True will improve UX by showing the scenario canvas as early as possible and then drawing individual plots as their data become available

# Maximum frames to render in the scenario tab per second, must be between 1-60.
#   Use lower values when running nuBoard in the cloud to prevent frame queues due to latency. The rule of thumb
#   is to match the frame rate with the expected latency, e.g 5Hz for 200ms round-trip latency:
scenario_rendering_frame_rate_cap_hz: 60
