defaults:
  # - common_metrics  # Uncomment this for common information about the scenario as specified in the config
  - low_level:  # Low level metrics
      - planner_expert_average_l2_error_within_bound_statistics
  - high_level:  # High level metrics that depend on low level metrics, they can also rely on the previously called high level metrics
      - planner_expert_final_l2_error_within_bound_statistics
      - planner_miss_rate_within_bound_statistics
      - planner_expert_final_heading_error_within_bound_statistics
      - planner_expert_average_heading_error_within_bound_statistics
