_target_: nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_utils.ScenarioMapping
_convert_: 'all'

# The default sampling rate for scenarios.
# Will be used for all unknown scenarios as well as those with subsample ratio not specified
subsample_ratio_override: 0.5

# List of scenarios and their extraction instructions:
#   scenario_name: name of scenario (e.g. ego overtaking)
#   scenario_duration: duration of the scenario (e.g. extract 20s from when the event occurred)
#   extraction_offset: [s] offset of the scenario (e.g. start at -5s from when the event occurred)
#   subsample_ratio: ratio used sample the scenario (e.g. a 0.1 ratio means sample from 20Hz to 2Hz). If not provided, then `subsample_ratio_override` will be used.

scenario_map:
  # scenario_name: [scenario_duration, extraction_offset, subsample_ratio]
  accelerating_at_crosswalk: [15.0, -3.0]
  accelerating_at_stop_sign: [15.0, -3.0]
  accelerating_at_stop_sign_no_crosswalk: [15.0, -3.0]
  accelerating_at_traffic_light: [15.0, -3.0]
  accelerating_at_traffic_light_with_lead: [15.0, -3.0]
  accelerating_at_traffic_light_without_lead: [15.0, -3.0]
  behind_bike: [15.0, -3.0]
  behind_long_vehicle: [15.0, -3.0]
  behind_pedestrian_on_driveable: [15.0, -3.0]
  behind_pedestrian_on_pickup_dropoff: [15.0, -3.0]
  changing_lane: [15.0, -3.0]
  changing_lane_to_left: [15.0, -3.0]
  changing_lane_to_right: [15.0, -3.0]
  changing_lane_with_lead: [15.0, -3.0]
  changing_lane_with_trail: [15.0, -3.0]
  crossed_by_bike: [15.0, -3.0]
  crossed_by_vehicle: [15.0, -3.0]
  following_lane_with_lead: [15.0, -3.0]
  following_lane_with_slow_lead: [15.0, -3.0]
  following_lane_without_lead: [15.0, -3.0]
  high_lateral_acceleration: [15.0, -3.0]
  high_magnitude_jerk: [15.0, -3.0]
  high_magnitude_speed: [15.0, -3.0]
  low_magnitude_speed: [15.0, -3.0]
  medium_magnitude_speed: [15.0, -3.0]
  near_barrier_on_driveable: [15.0, -3.0]
  near_construction_zone_sign: [15.0, -3.0]
  near_high_speed_vehicle: [15.0, -3.0]
  near_long_vehicle: [15.0, -3.0]
  near_multiple_bikes: [15.0, -3.0]
  near_multiple_pedestrians: [15.0, -3.0]
  near_multiple_vehicles: [15.0, -3.0]
  near_pedestrian_at_pickup_dropoff: [15.0, -3.0]
  near_pedestrian_on_crosswalk: [15.0, -3.0]
  near_pedestrian_on_crosswalk_with_ego: [15.0, -3.0]
  near_trafficcone_on_driveable: [15.0, -3.0]
  on_all_way_stop_intersection: [15.0, -3.0]
  on_carpark: [15.0, -3.0]
  on_intersection: [15.0, -3.0]
  on_pickup_dropoff: [15.0, -3.0]
  on_stopline_crosswalk: [15.0, -3.0]
  on_stopline_stop_sign: [15.0, -3.0]
  on_stopline_traffic_light: [15.0, -3.0]
  on_traffic_light_intersection: [15.0, -3.0]
  starting_high_speed_turn: [15.0, -3.0]
  starting_left_turn: [15.0, -3.0]
  starting_low_speed_turn: [15.0, -3.0]
  starting_protected_cross_turn: [15.0, -3.0]
  starting_protected_noncross_turn: [15.0, -3.0]
  starting_right_turn: [15.0, -3.0]
  starting_straight_stop_sign_intersection_traversal: [15.0, -3.0]
  starting_straight_traffic_light_intersection_traversal: [15.0, -3.0]
  starting_u_turn: [15.0, -3.0]
  starting_unprotected_cross_turn: [15.0, -3.0]
  starting_unprotected_noncross_turn: [15.0, -3.0]
  stationary: [15.0, -3.0]
  stationary_at_crosswalk: [15.0, -3.0]
  stationary_at_traffic_light_with_lead: [15.0, -3.0]
  stationary_at_traffic_light_without_lead: [15.0, -3.0]
  stationary_in_traffic: [15.0, -3.0]
  stopping_at_crosswalk: [15.0, -3.0]
  stopping_at_stop_sign_no_crosswalk: [15.0, -3.0]
  stopping_at_stop_sign_with_lead: [15.0, -3.0]
  stopping_at_stop_sign_without_lead: [15.0, -3.0]
  stopping_at_traffic_light_with_lead: [15.0, -3.0]
  stopping_at_traffic_light_without_lead: [15.0, -3.0]
  stopping_with_lead: [15.0, -3.0]
  traversing_crosswalk: [15.0, -3.0]
  traversing_intersection: [15.0, -3.0]
  traversing_narrow_lane: [15.0, -3.0]
  traversing_pickup_dropoff: [15.0, -3.0]
  traversing_traffic_light_intersection: [15.0, -3.0]
  waiting_for_pedestrian_to_cross: [15.0, -3.0]
