imitation_objective:
  _target_: nuplan.planning.training.modeling.objectives.trajectory_weight_decay_imitation_objective.TrajectoryWeightDecayImitationObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
