ego_expert_l2_error_with_yaw_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.ego_expert_l2_error_with_yaw.EgoExpertL2ErrorWithYawStatistics
  _convert_: 'all'
  name: 'ego_expert_l2_error_with_yaw'
  category: 'Planning'
  discount_factor: 1
  heading_diff_weight: 2.5
